polling-app/pollingapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pollingapps.urls"))
]

polling-app/pollingapps/urls.py
from django.urls import path

from . import views

app_name = 'pollingapps'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name="detail"),
    path('<int:question_id>/results', views.results, name="results"),
    path('<int:question_id>/vote', views.vote, name="vote")
]

polling-app/pollingapps/models.py
from django.db import models
import datetime
# Create your models here.
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def is_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedetlta(days=1)


class Choice(models.Model):
    # a choice can only have one Question
    # many choices one question
    # a choice cannot have multiple questions
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polling-app/pollingapps/forms.py
from django import forms

CHOICES = [(2, "sanjeevi")]


class RadioForm(forms.Form):
    '''
def __init__(self, CHOICES):
    # self.CHOICES = kwargs.pop('CHOICES')
    super().__init__()
    # self.choices = [(1, "Sanjeevi")]
    self.fields['choose_occupation'].choices = CHOICES
    print(CHOICES)
choose_occupation = forms.ChoiceField(widget=forms.RadioSelect())
    '''
    choose_occupation = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

polling-app/pollingapps/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# Create your views here.
from .models import Question
from .forms import RadioForm
from django.db.models import F


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'pollingapps/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    CHOICES_1 = []
    for choice in question.choice_set.all():
        CHOICES_1.append((choice.id, choice.choice_text))
    #form = RadioForm(CHOICES=CHOICES_1)
    form = RadioForm()
    form.fields['choose_occupation'].choices = CHOICES_1
    #form.choices = CHOICES_1
    # print(form.choices)
    context = {'RadioForm': form, 'question': question}
    return render(request, 'pollingapps/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    totalvotes = 0
    for choice in question.choice_set.all():
        totalvotes += choice.votes
    totalvotes = int(500 / totalvotes)
    print(totalvotes)
    context = {'question': question, 'totalvotes': totalvotes}
    return render(request, "pollingapps/results.html", context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    print(request.POST)
    selected_choice = question.choice_set.get(id=request.POST["choose_occupation"])
    print(selected_choice)
    selected_choice.votes += 1
    selected_choice.save()
    return redirect('pollingapps:results', question_id=question.id)

polling-app/pollingapps/templates/pollingapps/detail.html
<form action="{% url 'pollingapps:vote' question.id %}" method="post">
    {% csrf_token %}
    {{ RadioForm.as_p }}
    <button name="submit">Register</button>
</form>

polling-app/pollingapps/templates/pollingapps/detail1.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polling-app/pollingapps/templates/pollingapps/index.html
{% if latest_question_list %}
<ul>
	{% for question in latest_question_list %}
	<li><a href="{% url 'pollingapps:detail' question.id %}">{{ question.question_text}}</a></li>
	{% endfor %}
</ul>
{% endif %}

polling-app/pollingapps/templates/pollingapps/results.html
<ul>
{%for choice in question.choice_set.all%}
	<style>
	.Rectangle{{choice.id}}{
		width:  {% widthratio choice.votes 1 totalvotes  %}px;
		height: 20px;
		background-color: grey;
	}
	</style>
	<!-- Rectangle in div and style ensure that each rectangle has a different name -->

	<li> {{ choice}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	<div class=Rectangle{{choice.id}}></div>
{%endfor%}
</ul>

<a href="{% url 'pollingapps:detail' question.id %}">Exit</a>